{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kubecenter.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecenter.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "kubecenter.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
{{- end }}
