// Contrast test — verifies every theme generated by `themes.g.dart`
// guarantees the WCAG 2.2 AA contract for the primary text tokens.
//
// Per the M5 PR-5h plan R6, the explicit contract is:
//   - textPrimary on bgBase: ≥4.5:1
//   - textSecondary on bgSurface: ≥4.5:1
//
// The kitchen sink expands that to the full body-text matrix that the
// app actually composes — textPrimary across all three background tiers
// (base / surface / elevated) plus textSecondary on both bgBase and
// bgSurface. textMuted and the saturated state tokens (success, warning,
// error, info) are intentionally excluded:
//   - textMuted is caption-grade emphasis (rendered at fontSize 10–12 in
//     timestamp/byline contexts) and is meant to fall under WCAG AA
//     Large at 3:1, not Normal at 4.5:1.
//   - State pills composite the saturated tone onto a same-coloured Dim
//     background (e.g. `error` text on `errorDim` fill) — the effective
//     foreground/background pair is determined at composite time, not at
//     theme generation time, so a textContrastGuideline assertion on
//     `error` against raw `bgSurface` would be misleading.
//
// If a theme breaks one of the asserted pairs, the test fails and points
// at the theme id; remediate by editing `shared/themes/<theme>.json`
// (one-line luminance bump on textPrimary or textSecondary), then run
// `make check-themes` to regenerate `themes.g.dart`.

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:kubecenter/theme/kube_theme_builder.dart';
import 'package:kubecenter/theme/themes.g.dart';

import '../a11y_helpers.dart';

class _BodyTextMatrix extends StatelessWidget {
  const _BodyTextMatrix();

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).extension<KubeColors>()!;
    return ColoredBox(
      color: colors.bgBase,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // textPrimary at body size on every background tier.
          _row(colors.bgBase, [
            Text('Primary body on base',
                style: TextStyle(color: colors.textPrimary, fontSize: 16)),
          ]),
          _row(colors.bgSurface, [
            Text('Primary body on surface',
                style: TextStyle(color: colors.textPrimary, fontSize: 16)),
          ]),
          _row(colors.bgElevated, [
            Text('Primary body on elevated',
                style: TextStyle(color: colors.textPrimary, fontSize: 16)),
          ]),
          // textSecondary at info-row subtitle size on the three surfaces
          // where it actually renders (bgBase under section headers,
          // bgSurface under card titles, bgElevated in unread-notification
          // message bodies at feed_screen.dart:218).
          _row(colors.bgBase, [
            Text('Secondary subtitle on base',
                style: TextStyle(color: colors.textSecondary, fontSize: 14)),
          ]),
          _row(colors.bgSurface, [
            Text('Secondary subtitle on surface',
                style: TextStyle(color: colors.textSecondary, fontSize: 14)),
          ]),
          _row(colors.bgElevated, [
            Text('Secondary subtitle on elevated',
                style: TextStyle(color: colors.textSecondary, fontSize: 12)),
          ]),
        ],
      ),
    );
  }

  Widget _row(Color background, List<Widget> children) {
    return ColoredBox(
      color: background,
      child: Padding(
        padding: const EdgeInsets.all(12),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            for (final c in children)
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 4),
                child: c,
              ),
          ],
        ),
      ),
    );
  }
}

void main() {
  for (final entry in kubeThemes.entries) {
    final id = entry.key;
    final name = entry.value.name;
    testWidgets(
        '$name ($id): body-text/background pairs meet textContrastGuideline',
        (tester) async {
      await tester.pumpWidget(a11yHarness(
        theme: buildKubeTheme(id),
        child: const _BodyTextMatrix(),
      ));
      await expectMeetsAllGuidelines(
        tester,
        textContrast: true,
        // Tap-target and label guidelines aren't meaningful for a static
        // text-only widget; the dedicated tests handle those.
        iOSTapTarget: false,
        androidTapTarget: false,
        labeledTapTargets: false,
      );
    });
  }
}
