// GENERATED by tools/theme-gen/main.ts — do not edit by hand.
// Source: shared/themes/*.json. Regenerate via `deno task theme-gen`
// (or `make check-themes` in CI).

/// Pure-Dart colour tokens for each k8sCenter theme. Consumed by
/// kube_theme_builder.dart to build Flutter ThemeData + the KubeColors
/// ThemeExtension. Kept as a plain Dart library so CI parity checks
/// work without a Flutter toolchain.
class KubeThemeColors {
  const KubeThemeColors({
    required this.bgBase,
    required this.bgSurface,
    required this.bgElevated,
    required this.bgHover,
    required this.borderPrimary,
    required this.borderSubtle,
    required this.textPrimary,
    required this.textSecondary,
    required this.textMuted,
    required this.accent,
    required this.accentGlow,
    required this.accentDim,
    required this.accentSecondary,
    required this.accent2,
    required this.success,
    required this.successDim,
    required this.warning,
    required this.warningDim,
    required this.error,
    required this.errorDim,
    required this.info,
    required this.glassSurface,
    required this.glassElevated,
    required this.glassBorder,
    required this.glassHighlight,
    required this.glassScrim,
    required this.glassRimLight,
    required this.glassRimSoft,
    required this.glassRimDark,
  });

  final String bgBase;
  final String bgSurface;
  final String bgElevated;
  final String bgHover;
  final String borderPrimary;
  final String borderSubtle;
  final String textPrimary;
  final String textSecondary;
  final String textMuted;
  final String accent;
  final String accentGlow;
  final String accentDim;
  final String accentSecondary;
  final String accent2;
  final String success;
  final String successDim;
  final String warning;
  final String warningDim;
  final String error;
  final String errorDim;
  final String info;
  final String glassSurface;
  final String glassElevated;
  final String glassBorder;
  final String glassHighlight;
  final String glassScrim;
  final String glassRimLight;
  final String glassRimSoft;
  final String glassRimDark;
}

class KubeTheme {
  const KubeTheme({
    required this.id,
    required this.name,
    required this.colors,
  });

  final String id;
  final String name;
  final KubeThemeColors colors;
}

const Map<String, KubeTheme> kubeThemes = {
  'liquid-glass': KubeTheme(
    id: 'liquid-glass',
    name: 'Liquid Glass',
    colors: KubeThemeColors(
      bgBase: '#080b16',
      bgSurface: '#0d1322',
      bgElevated: '#141b2d',
      bgHover: '#1b2440',
      borderPrimary: '#243150',
      borderSubtle: '#19223a',
      textPrimary: '#eef2fb',
      textSecondary: '#9aa6c4',
      textMuted: '#647189',
      accent: '#43b0ff',
      accentGlow: 'rgba(67, 174, 255, 0.16)',
      accentDim: 'rgba(67, 174, 255, 0.12)',
      accentSecondary: '#9b87ff',
      accent2: '#9b87ff',
      success: '#34d399',
      successDim: 'rgba(52, 211, 153, 0.12)',
      warning: '#fbbf24',
      warningDim: 'rgba(251, 191, 36, 0.12)',
      error: '#fb7185',
      errorDim: 'rgba(251, 113, 133, 0.12)',
      info: '#7dd3fc',
      glassSurface: 'rgba(15, 21, 38, 0.55)',
      glassElevated: 'rgba(22, 30, 52, 0.66)',
      glassBorder: 'rgba(150, 178, 228, 0.16)',
      glassHighlight: 'rgba(255, 255, 255, 0.07)',
      glassScrim: 'rgba(4, 7, 14, 0.55)',
      glassRimLight: 'rgba(255, 255, 255, 0.16)',
      glassRimSoft: 'rgba(255, 255, 255, 0.06)',
      glassRimDark: 'rgba(0, 0, 0, 0.30)',
    ),
  ),
  'liquid-glass-light': KubeTheme(
    id: 'liquid-glass-light',
    name: 'Liquid Glass Light',
    colors: KubeThemeColors(
      bgBase: '#eaeef6',
      bgSurface: '#ffffff',
      bgElevated: '#ffffff',
      bgHover: '#eef3fa',
      borderPrimary: '#d6deec',
      borderSubtle: '#e7ecf5',
      textPrimary: '#141a2b',
      textSecondary: '#4d5972',
      textMuted: '#8492ad',
      accent: '#2a7fe0',
      accentGlow: 'rgba(42, 127, 224, 0.16)',
      accentDim: 'rgba(42, 127, 224, 0.10)',
      accentSecondary: '#7a63f0',
      accent2: '#7a63f0',
      success: '#10a877',
      successDim: 'rgba(16, 168, 119, 0.12)',
      warning: '#d99411',
      warningDim: 'rgba(217, 148, 17, 0.12)',
      error: '#e0556a',
      errorDim: 'rgba(224, 85, 106, 0.12)',
      info: '#3aa0d8',
      glassSurface: 'rgba(255, 255, 255, 0.62)',
      glassElevated: 'rgba(255, 255, 255, 0.80)',
      glassBorder: 'rgba(40, 60, 110, 0.13)',
      glassHighlight: 'rgba(255, 255, 255, 0.60)',
      glassScrim: 'rgba(214, 222, 236, 0.55)',
      glassRimLight: 'rgba(255, 255, 255, 0.85)',
      glassRimSoft: 'rgba(255, 255, 255, 0.50)',
      glassRimDark: 'rgba(60, 80, 120, 0.10)',
    ),
  ),
};

const String defaultThemeId = 'liquid-glass';
