// Single-source theme generator.
//
// Reads shared/themes/*.json (the canonical token definitions consumed by
// both web and mobile) and emits two artifacts that are checked into the
// repo:
//
//   frontend/assets/themes.generated.css
//     Imported by frontend/assets/styles.css. Contains only the per-theme
//     CSS variable blocks — :root for the default theme, [data-theme="<id>"]
//     for the others.
//
//   mobile/lib/theme/themes.g.dart
//     Stub Dart file with a KubeThemeColors data class and a static map
//     keyed by theme id. The Flutter app will import this directly. Until
//     PR-1 (`flutter create mobile/`) lands, the stub is a regular Dart
//     library that compiles standalone — this lets the parity check work
//     without a full Flutter toolchain in CI.
//
// Usage:
//   deno run -A tools/theme-gen/main.ts          # write artifacts
//   deno run -A tools/theme-gen/main.ts --check  # exit non-zero if drifted
//
// The --check mode is what `make check-themes` calls in CI: it regenerates
// in-memory and diffs against the committed files. Drift fails the build.

import { resolve } from "jsr:@std/path@^1";

interface Theme {
  id: string;
  name: string;
  default?: boolean;
  colors: Record<string, string>;
}

const ROOT = resolve(import.meta.dirname!, "..", "..");
const THEMES_DIR = resolve(ROOT, "shared", "themes");
const CSS_OUT = resolve(ROOT, "frontend", "assets", "themes.generated.css");
const DART_OUT = resolve(
  ROOT,
  "mobile",
  "lib",
  "theme",
  "themes.g.dart",
);

// Theme load order matches the existing styles.css for diff stability.
const ORDER = [
  "nexus",
  "dracula",
  "tokyo-night",
  "catppuccin",
  "nord",
  "one-dark",
  "gruvbox",
];

const CSS_VAR_MAP: Record<string, string> = {
  bgBase: "--bg-base",
  bgSurface: "--bg-surface",
  bgElevated: "--bg-elevated",
  bgHover: "--bg-hover",
  borderPrimary: "--border-primary",
  borderSubtle: "--border-subtle",
  textPrimary: "--text-primary",
  textSecondary: "--text-secondary",
  textMuted: "--text-muted",
  accent: "--accent",
  accentGlow: "--accent-glow",
  accentDim: "--accent-dim",
  accentSecondary: "--accent-secondary",
  success: "--success",
  successDim: "--success-dim",
  warning: "--warning",
  warningDim: "--warning-dim",
  error: "--error",
  errorDim: "--error-dim",
  info: "--info",
};

async function loadThemes(): Promise<Theme[]> {
  const themes: Theme[] = [];
  for (const id of ORDER) {
    const path = resolve(THEMES_DIR, `${id}.json`);
    const text = await Deno.readTextFile(path);
    const t = JSON.parse(text) as Theme;
    if (t.id !== id) {
      throw new Error(
        `theme id mismatch in ${path}: filename=${id} json.id=${t.id}`,
      );
    }
    for (const key of Object.keys(CSS_VAR_MAP)) {
      if (!(key in t.colors)) {
        throw new Error(`theme ${id} missing colour token: ${key}`);
      }
    }
    themes.push(t);
  }
  return themes;
}

function emitCss(themes: Theme[]): string {
  const lines: string[] = [
    "/* GENERATED by tools/theme-gen/main.ts — do not edit by hand. */",
    "/* Source: shared/themes/*.json. Run `deno task theme-gen` (or */",
    "/* `make check-themes` in CI) to regenerate. */",
    "",
  ];

  for (const t of themes) {
    const selector = t.default ? ":root" : `[data-theme="${t.id}"]`;
    lines.push(`/* ── ${t.name} ── */`);
    lines.push(`${selector} {`);
    for (const [key, cssVar] of Object.entries(CSS_VAR_MAP)) {
      lines.push(`  ${cssVar}: ${t.colors[key].toLowerCase()};`);
    }
    lines.push(`}`);
    lines.push("");
  }

  return lines.join("\n");
}

function dartFieldName(key: string): string {
  return key; // already camelCase
}

function emitDart(themes: Theme[]): string {
  const lines: string[] = [
    "// GENERATED by tools/theme-gen/main.ts — do not edit by hand.",
    "// Source: shared/themes/*.json. Regenerate via `deno task theme-gen`",
    "// (or `make check-themes` in CI).",
    "",
    "/// Pure-Dart colour tokens for each k8sCenter theme. PR-1 will wrap",
    "/// these into Flutter ThemeData + ThemeExtension instances; until then",
    "/// the file lives as a plain Dart library so CI parity checks work",
    "/// without a Flutter toolchain.",
    "class KubeThemeColors {",
    "  const KubeThemeColors({",
  ];
  for (const key of Object.keys(CSS_VAR_MAP)) {
    lines.push(`    required this.${dartFieldName(key)},`);
  }
  lines.push("  });");
  lines.push("");
  for (const key of Object.keys(CSS_VAR_MAP)) {
    lines.push(`  final String ${dartFieldName(key)};`);
  }
  lines.push("}");
  lines.push("");
  lines.push("class KubeTheme {");
  lines.push("  const KubeTheme({");
  lines.push("    required this.id,");
  lines.push("    required this.name,");
  lines.push("    required this.colors,");
  lines.push("  });");
  lines.push("");
  lines.push("  final String id;");
  lines.push("  final String name;");
  lines.push("  final KubeThemeColors colors;");
  lines.push("}");
  lines.push("");
  lines.push("const Map<String, KubeTheme> kubeThemes = {");
  for (const t of themes) {
    lines.push(`  '${t.id}': KubeTheme(`);
    lines.push(`    id: '${t.id}',`);
    lines.push(`    name: '${t.name}',`);
    lines.push("    colors: KubeThemeColors(");
    for (const key of Object.keys(CSS_VAR_MAP)) {
      lines.push(`      ${dartFieldName(key)}: '${t.colors[key]}',`);
    }
    lines.push("    ),");
    lines.push("  ),");
  }
  lines.push("};");
  lines.push("");
  const defaultTheme = themes.find((t) => t.default) ?? themes[0];
  lines.push(`const String defaultThemeId = '${defaultTheme.id}';`);
  lines.push("");
  return lines.join("\n");
}

async function main() {
  const check = Deno.args.includes("--check");
  const themes = await loadThemes();
  const css = emitCss(themes);
  const dart = emitDart(themes);

  if (check) {
    const errors: string[] = [];
    const existingCss = await Deno.readTextFile(CSS_OUT).catch(() => "");
    if (existingCss !== css) {
      errors.push(`drift detected: ${CSS_OUT}`);
    }
    const existingDart = await Deno.readTextFile(DART_OUT).catch(() => "");
    if (existingDart !== dart) {
      errors.push(`drift detected: ${DART_OUT}`);
    }
    if (errors.length > 0) {
      console.error("theme-gen check failed:");
      for (const e of errors) console.error("  -", e);
      console.error(
        "\nRun `deno run -A tools/theme-gen/main.ts` and commit the result.",
      );
      Deno.exit(1);
    }
    console.log("themes in sync");
    return;
  }

  await Deno.mkdir(resolve(ROOT, "mobile", "lib", "theme"), {
    recursive: true,
  });
  await Deno.writeTextFile(CSS_OUT, css);
  await Deno.writeTextFile(DART_OUT, dart);
  console.log(`wrote ${CSS_OUT}`);
  console.log(`wrote ${DART_OUT}`);
}

if (import.meta.main) {
  await main();
}
